version: '3'
services:

  bplan-frontend:    
    privileged: true
    container_name: bplan-frontend
    image: thomasreulen/bplan-frontend:latest    
    working_dir: /home/node/app
    build: 
      context: ./frontend
      dockerfile: ./container/Dockerfile
    environment:
      - NODE_ENV=devleopment
    volumes:
      - ./frontend/assets:/assets
      - ./frontend/project:/home/node/app/
      - nodemods:/home/node/app/node_modules:rw
    restart: always
    command: [ "sleep", "16000" ]
    ports:
      - 3000:3000

  bplan-web:
    container_name: bplan-web
    image: nginx:1.24 
    volumes: 
      - ./frontend/project/www:/usr/share/nginx/html:ro
    ports:
      - 80:80
      
  adinlte-web:
    container_name: adminlte-web
    image: nginx:1.24 
    volumes: 
      - ./frontend/assets/AdminLTE-3.2.0/:/usr/share/nginx/html:ro
    ports:
      - 81:80

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    environment: 
      - SWAGGER_JSON=/apispec/v1.yml
    volumes: 
      - ./swagger:/apispec
    ports:
      - "88:8080"

  petstore:
    container_name: petstore
    image: swaggerapi/swagger-ui
    environment: 
      - SWAGGER_JSON=/apispec/petstore.yml
    volumes: 
      - ./swagger:/apispec
    ports:
      - "89:8080"

  api: 
    container_name: bplanner-api 
    image: thomasreulen/bplan-api:latest  
    build: 
      context: ./api
      dockerfile: ./src/Dockerfile
    volumes:
      - ./api:/home/tom/api
    environment: 
      - DB_HOST=127.0.0.1
      - DB_PORT=1234
    ports: 
      - "8080:8080"
    command: [ "sleep", "16000" ]
      
volumes:
  nodemods: